feat: multi-arch
typesense/typesense-docsearch-scraper pull request #58
Opened 2024-03-25 11:05 UTC by darkweaver87

## Change Summary
This PR uses docker multi-stage feature and and multi-arch build.
It also updates to python 3.11 (version on debian) and use chromium instead of chrome to support multi-arch easily.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

2024-04-06 00:48 UTC, jasonbosco requested changes
Could you still keep the base image separate from the image that places the latest code inside the base image? 

The base image takes a while to build and doesn't need to be rebuilt each time the scraper code changes, which is why these are two separate images.

2024-07-10 15:24 UTC, darkweaver87 commented
Sorry for late answer @jasonbosco. I can do it but I don't get your point actually :-)
The dockerfile is a multi-stage one. So each stage can be built separately if needed and a change in the code won't trigger a full rebuild of the base image and you can even specify which target you want to build. Example building `test` image:

```bash
$ docker buildx build -t typesense-docsearch-scraper:latest --platform=linux/amd64 --load . -f scraper/dev/docker/Dockerfile --target test
[+] Building 215.9s (31/31) FINISHED                                                                                                                                                 docker-container:nifty_pascal
 => [internal] booting buildkit                                                                                                                                                                              13.5s
 => => pulling image moby/buildkit:buildx-stable-1                                                                                                                                                           12.4s
 => => creating container buildx_buildkit_nifty_pascal0                                                                                                                                                       1.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 1.79kB                                                                                                                                                                        0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1.4                                                                                                                                   1.2s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                                                                                              0.0s
 => docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                                    1.2s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                                        0.0s
 => => sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB                                                                                                                1.0s
 => => extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546                                                                                                                     0.1s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 267B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/debian:12-slim                                                                                                                                             1.4s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                             0.1s
 => => transferring context: 1.86MB                                                                                                                                                                           0.0s
 => [base  1/17] FROM docker.io/library/debian:12-slim@sha256:f528891ab1aa484bf7233dbcc84f3c806c3e427571d75510a9d74bb5ec535b33                                                                                3.3s
 => => resolve docker.io/library/debian:12-slim@sha256:f528891ab1aa484bf7233dbcc84f3c806c3e427571d75510a9d74bb5ec535b33                                                                                       0.0s
 => => sha256:f11c1adaa26e078479ccdd45312ea3b88476441b91be0ec898a7e07bfd05badc 29.13MB / 29.13MB                                                                                                              2.7s
 => => extracting sha256:f11c1adaa26e078479ccdd45312ea3b88476441b91be0ec898a7e07bfd05badc                                                                                                                     0.5s
 => [base  2/17] RUN useradd -d /home/seleuser -m seleuser                                                                                                                                                    0.2s
 => [base  3/17] RUN chown -R seleuser /home/seleuser                                                                                                                                                         0.1s
 => [base  4/17] RUN chgrp -R seleuser /home/seleuser                                                                                                                                                         0.1s
 => [base  5/17] WORKDIR /home/seleuser                                                                                                                                                                       0.0s
 => [base  6/17] RUN apt-get update -y && apt-get install -yq     software-properties-common    python3                                                                                                      23.2s
 => [base  7/17] RUN apt-get update -y && apt-get install -yq     curl     wget     sudo     gnupg     && curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -                                        8.1s 
 => [base  8/17] RUN apt-get update -y && apt-get install -y     nodejs                                                                                                                                       5.8s 
 => [base  9/17] RUN apt-get update -y && apt-get install -yq   unzip   xvfb   libxi6   libgconf-2-4   default-jdk                                                                                           38.3s 
 => [base 10/17] RUN apt-get update -y && apt-get install -yq   chromium-driver                                                                                                                              29.7s 
 => [base 11/17] RUN wget -q https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar                                                                                3.0s 
 => [base 12/17] RUN wget -q https://repo1.maven.org/maven2/org/testng/testng/7.6.1/testng-7.6.1.jar                                                                                                          0.4s 
 => [base 13/17] COPY Pipfile .                                                                                                                                                                               0.1s 
 => [base 14/17] COPY Pipfile.lock .                                                                                                                                                                          0.1s 
 => [base 15/17] RUN apt-get update -y && apt-get install -yq     python3-pip                                                   [...]

2024-08-26 22:14 UTC, jasonbosco commented
@darkweaver87 Docker cache only works when using the same machine to run consecutive docker builds. If we need to run this in CI (without any cache, since at least with GitHub actions saving any form of cache usually takes a long time), then we'd end up rebuilding all layers every CI run. 

It would be nice to keep CI fast, and also the base images separate.

2024-09-30 13:39 UTC, darkweaver87 commented
You can still use the `--cache-from` option  (I'm using it in my own CI to build scraper en ARM) but if it's more convenient for you then I will rebase and switch back to multiple files.

2024-09-30 16:19 UTC, jasonbosco commented
Yeah multiple files would be ideal

2024-10-01 10:17 UTC, darkweaver87 commented
Done :-)
FYI, I faced when [an issue](https://github.com/SeleniumHQ/selenium/issues/14457#issuecomment-2385382102) since chromium has been upgraded in debian since my last PR.

2024-10-09 19:01 UTC, jasonbosco approved these changes

2024-10-09 19:01 UTC, merged

2024-10-09 21:47 UTC, jasonbosco commented
@darkweaver87 Thank you again for the PR. I've published the changes in this Docker Image: `typesense/docsearch-scraper:0.11.0.rc1`. 

Could you give it a shot and let me know how it goes?

2024-10-10 07:01 UTC, darkweaver87 commented
@jasonbosco I just tested `typesense/docsearch-scraper:0.11.0.rc1` on my infrastructure (which runs on aws/t4g) and it works perfectly. Many thanks.

2024-10-10 19:41 UTC, jasonbosco commented
Awesome, thank you for confirming!